import UserService from "@repo/services/user";
import GmailService from "@repo/services/gmail";
import CalendarService from "@repo/services/calendar";
import RunCorsairAgent from "@repo/services/open-ai_SDK";
import ChatService from "@repo/services/chat";
import RagService from "@repo/services/rag";
import CorsairApprovalService from "@repo/services/corsair-approvals";
export const userService = new UserService();
export const gmailService = new GmailService();
export const calendarService = new CalendarService();
export const CorsairAgent = RunCorsairAgent;
export const chatService = new ChatService();
export const ragService = new RagService();
export const corsairApprovalService = new CorsairApprovalService();
